swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger Product-Service
  license:
    url: http://www.apache.org/licenses/LICENSE-2.0.html
    name: Apache 2.0
host: j90gusfcc8.execute-api.eu-west-1.amazonaws.com
basePath: /dev
tags:
- name: products
schemes:
- https
paths:
  /products:
    get:
      tags:
      - products
      summary: Get list of all products
      operationId: getProducts
      produces:
      - application/json
      - application/xml
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/ProductResponse'
  /products/{productId}:
    get:
      tags:
      - products
      summary: Get product by ID
      description: Returns a single product
      operationId: getProductById
      produces:
      - application/json
      - application/xml
      parameters:
      - name: productId
        in: path
        description: ID of product to return
        required: true
        type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/ProductResponse'
        400:
          description: Invalid ID supplied
        404:
          description: Product not found
definitions:
  Product:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      description:
        type: string
      price:
        type: number
        format: double
      img:
        type: string
    xml:
      name: Order
  ProductResponse:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/Product'
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
